# Generated by Django 2.1.1 on 2018-10-05 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key_type', models.CharField(max_length=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.key')),
            ],
        ),
    ]
