# Generated by Django 2.1.1 on 2018-11-02 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20181102_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyType',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('785dafc9-3cfb-40ee-b26d-87c083a10bfb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='key_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.keyType'),
        ),
    ]
