# Generated by Django 2.1.1 on 2018-11-02 21:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_auto_20181102_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b3b5d1f4-49e9-4a85-a85b-54260c4700e6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keys.key'),
        ),
    ]
