# Generated by Django 2.1.3 on 2018-11-05 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_auto_20181102_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='keys.keyType')),
            ],
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('605dd618-cd29-441d-a71e-a20966ec71f6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='key',
            name='created_for',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='keys.tenant'),
        ),
    ]
