# Generated by Django 2.1.3 on 2018-11-07 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0007_auto_20181107_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('738e95bf-ca98-4f36-b39d-4a389f79950a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
