# Generated by Django 2.1.7 on 2019-03-10 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_auto_20181107_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('keys.key',),
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aeb69c8d-5f99-4e98-98e3-1f414519b464'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'key_type': 'G'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='keys.key'),
        ),
        migrations.AlterField(
            model_name='key',
            name='valid_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38da019d-fe19-4ff0-bc48-75b58a202d18'), editable=False, primary_key=True, serialize=False),
        ),
    ]
