# Generated by Django 2.1.7 on 2019-03-10 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0009_auto_20190310_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='keyAdmin',
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ed61c53-7efb-4212-a270-564b06274f0d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('116d5dcc-bebb-44dd-8a99-b75bae793870'), editable=False, primary_key=True, serialize=False),
        ),
    ]
