# Generated by Django 2.1.7 on 2019-03-10 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0010_auto_20190310_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e3f4743-7c90-495d-bb59-a232ce7c2d35'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
