# Generated by Django 2.1.7 on 2019-03-12 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keys', '0011_auto_20190310_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48768b0c-08f2-403d-9656-41904e45394d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='keys.tenant'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
