# Generated by Django 2.1.7 on 2019-03-12 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0012_auto_20190312_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('826d844d-3eb2-44c6-baf0-316a33063aeb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.tenant'),
        ),
    ]
