# Generated by Django 2.1.7 on 2019-03-12 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0013_auto_20190312_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='key',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='deleted',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d6f8ef3-f300-487f-ac07-2d233ba749e7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
