# Generated by Django 2.1.7 on 2019-03-12 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0014_auto_20190312_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a07a5dd-3e4d-48c8-8c70-857a1b64dfbe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
