# Generated by Django 2.1.7 on 2019-03-12 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0015_auto_20190312_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='id',
        ),
        migrations.AddField(
            model_name='key',
            name='key_value',
            field=models.UUIDField(default=uuid.UUID('9e8a2c6e-4a38-4fcb-8d98-7805a166f788'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
