# Generated by Django 2.1.7 on 2019-03-12 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0016_auto_20190312_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_value',
            field=models.UUIDField(default=uuid.UUID('d8bec8e5-56d8-4361-a442-bf049f58180a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
