# Generated by Django 2.1.7 on 2019-03-12 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0017_auto_20190312_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_value',
            field=models.UUIDField(default=uuid.UUID('475f1eb6-d9fe-4ced-97cd-2f7bcae3de3b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
